# The testing matrix **for simp-packer** only considers ruby/puppet versions
# supported by SIMP:
# ------------------------------------------------------------------------------
#  release    pup   ruby     eol
# SIMP 6.0+   4.8   2.1.9    TBD***
# SIMP 6.2    4.10  2.1.9    TBD###
# SIMP 6.3+   5.5   2.4.4    TBD
#
# *** = Modules created for SIMP 6.2+ are not required to support Puppet < 4.10
# ### = Modules created for SIMP 6.3+ are not required to support Puppet < 5.3
# ==============================================================================
#
# Travis CI Repo options for this pipeline:
#
#   Travis CI Env Var      Type      Notes
#   ---------------------  --------  -------------------------------------------
#   GITHUB_OAUTH_TOKEN     Secure    Required for automated GitHub releases
#   SKIP_GITHUB_PUBLISH    Optional  Skips publishing GitHub releases if "true"
#
#   The secure env vars will be filtered in Travis CI log output, and aren't
#   provided to untrusted builds (i.e, triggered by PR from another repository)
#
# ------------------------------------------------------------------------------
#
# Travis CI Trigger options for this pipeline:
#
#   To validate if $GITHUB_OAUTH_TOKEN is able to publish a GitHub release,
#   trigger a custom Travis CI build for this branch using the CUSTOM CONFIG:
#
#     env: VALIDATE_TOKENS=yes
#
# ------------------------------------------------------------------------------
#
# Release Engineering notes:
#
#   To automagically publish a release to GitHub and PuppetForge:
#
#   - Set GITHUB_OAUTH_TOKEN as a secure env variable in this repo's Travis CI
#     settings
#   - Push a git tag that matches the lates version in CHANGELOG.md
#   - The tag SHOULD be annotated with release notes, but nothing enforces this
#     convention at present
#
# ------------------------------------------------------------------------------
---
language: ruby
cache: bundler
sudo: false
bundler_args: --without development system_tests --path .vendor
notifications:
  email: false

stages:
  - name: 'validate tokens'
    if: 'env(VALIDATE_TOKENS) = yes'
  - name: validation
    if: 'NOT env(VALIDATE_TOKENS) = yes'
  - name: 'Spec tests'
    if: 'NOT env(VALIDATE_TOKENS) = yes'
  - name: deploy
    if: 'tag IS present AND NOT env(VALIDATE_TOKENS) = yes'

before_install:
  - rm -f Gemfile.lock
  - gem update --system --no-document

jobs:
  ### allow_failures:
  ###   - name: 'Latest Puppet 5.x (allowed to fail)'
  ###   - name: 'Latest Puppet 6.x (allowed to fail)'

  include:
    ###  Testing on Travis CI is indefinitely disabled
    ###
    ###  See:
    ###    * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
    ###    * https://simp-project.atlassian.net/browse/SIMP-8703
    ###
    ###    - stage:  validation
    ###      name:   Rubocop
    ###      script: bundle exec rake test:rubocop
    ###
    ###    - stage:  validation
    ###      name:   Shellcheck
    ###      script: bundle exec rake test:shellcheck
    ###
    ###    - stage:  validation
    ###      name:   'Validate simp.json (packer 1.4.0)'
    ###      env:
    ###        - 'ver=1.4.0'
    ###        - 'PATH="$PWD/packer-bin/${ver}:${PATH}"'
    ###      before_script:
    ###        - 'test -f "packer-bin/${ver}/packer" || { wget -c "https://releases.hashicorp.com/packer/${ver}/packer_${ver}_linux_amd64.zip" -O packer.zip && mkdir -p "packer-bin/${ver}" && cd "packer-bin/${ver}" && unzip ../../packer.zip ; cd - ; }'
    ###        - 'packer --version'
    ###      script: bundle exec rake packer:validate
    ###
    ###    - stage: 'Spec tests'
    ###      rvm:    2.4.9
    ###      name:  'Ruby unit tests (Ruby 2.4.9)'
    ###      script: bundle exec rake spec
    ###
    ###    - stage:  'Spec tests'
    ###      name:   'Puppet 5.5 (SIMP 6.3+)'
    ###      rvm:    2.4.9
    ###      env:
    ###        - 'PUPPET_VERSION="~> 5.5.6"'
    ###      script: bundle exec rake test:puppet
    ###
    ###    - stage:  'Spec tests'
    ###      name:   'Latest Puppet 5.x (allowed to fail)'
    ###      rvm:    2.4.4
    ###      env:
    ###        - 'PUPPET_VERSION="~> 5.0"'
    ###      script: bundle exec rake test:puppet
    ###
    ###    - stage:  'Spec tests'
    ###      name: 'Puppet 6.18 (PE 2019.2)'
    ###      rvm: 2.5.7
    ###      env: PUPPET_VERSION="~> 6.18.0"
    ###      script:
    ###        - bundle exec rake spec
    ###
    ###    - stage:  'Spec tests'
    ###      name:   'Latest Puppet 6.x (allowed to fail)'
    ###      rvm:    2.5.7
    ###      env:
    ###        - 'PUPPET_VERSION="~> 6.0"'
    ###      script: bundle exec rake test:puppet

    - stage: deploy
      script:
        - true
      deploy:
        - provider: releases
          token: $GITHUB_OAUTH_TOKEN
          on:
            tags: true
            condition: '($SKIP_GITHUB_PUBLISH != true)'

    - stage: 'validate tokens'
      language: shell
      before_install: skip
      install: skip
      name:  'validate CI GitHub OAuth token has sufficient scope to release'
      script:
      - 'echo; echo "===== GITHUB_OAUTH_TOKEN validation";echo "  (TRAVIS_SECURE_ENV_VARS=$TRAVIS_SECURE_ENV_VARS)"; echo'
      - 'OWNER="$(echo $TRAVIS_REPO_SLUG | cut -d/ -f1)"'
      - 'curl -H "Authorization: token ${GITHUB_OAUTH_TOKEN}"
          "https://api.github.com/users/$OWNER"
          -I | grep ^X-OAuth-Scopes | egrep -w "repo|public_repo"'
